<!DOCTYPE html>
<html>
<head></head>
<body>
<h1>Real Proof</h1>
<p>
Before this repository, my GitHub had very little PHP on it... yet, I've written over 100 thousand lines of it! This repository is an attempt to fix that. 
</p>
<p>
I can't share the vast majority of the work I've done for other people (for obvious reasons), but I can share is code out of my own codebase. 
When reading these, please be conscious that they were coded in the context of a solo developer, and are lacking things like comments, and name-spacing. 
On group projects, being considerate of my peers is important to me. 
</p>
<p>
Also, some of these are dev tools only (input generated by a trusted user: myself)... 
Some of the security in these files (like prepared statements) would be inappropriate for public-facing production.
A lot of the meta-programming, like the creation of tables, could not be accomplished with prepared statements (I ran into the limits of MySQL). 
</p>
</body>
</html>